---
cog_bundle_version: 4

name: pi
version: 0.2.6
docker:
  image: pannet/pi-bundle
  tag: 0.2.6
description: Manage privacyidea user resources and tokens
long_description: >
  This bundle provides commands for viewing and manipulating users and token 
  in privacyidea.
  Permissions are used to control which users are authorized to run each command. 
  Listing and searching for resources requires the pi:read permission. 
  Modifying the objecs or other values of a resource requires the pi:write
  Some delete and revoke commands require pi:admin permission.
permissions:
  - pi:read
  - pi:write
  - pi:execute
  - pi:admin
config:
  notes: >
    Make sure the privacyidea user set in the environment variables has the necessary rights.
  env:
    - var: pi_fqdn
      description: privacyidea FQDN (missing schema default to https)
    - var: pi_username
      description: privacyidea username
    - var: pi_password
      description: privacyidea user's password
  homepage: https://gitlab.tools.in.pan-net.eu/cog-bundles/privacyidea
  author: Diogenes Santos de Jesus <diogenes.jesus@telekom.com>
commands:
  token-list:
    executable: /usr/bin/cog-subcommand
    description: List token for a given user
    long_description: >
      List tokens for a user
    examples: |
      * List tokens for a given user

          !pi:token-list <user> [<user> ...]
    rules:
        - must have pi:read
  token-reset:
    executable: /usr/bin/cog-subcommand
    description: Reset failcounter for all tokens of a user
    long_description: >
      Reset failcounter for all tokens of a user
    examples: |
      * Reset failcounter for all tokens of a user

          !pi:token-reset <user>
    rules:
        - must have pi:write
  token-delete:
    executable: /usr/bin/cog-subcommand
    description: Delete a token
    long_description: >
      Delete a token based on serial
    examples: |
      * Delete a token based on serial

          !pi:token-delete <serial> [<serial> ...]
    rules:
        - must have pi:admin
templates:
  token_list:
    body: |
      ~each var=$results as=user~
      ~if cond=length($user.tokens) == 0~
      ~attachment title=$user.name color="black"~
      No token assigned for ~$user.name~
      ~end~
      ~end~
      ~if cond=length($user.tokens) > 0~
      ~each var=$user.tokens as=token~
      ~if cond=$token.failcount >= 10~
      ~attachment title=$user.name color="red"~
      **Token Serial:** ~$token.serial~
      **Token Type**: ~$token.tokentype~
      **Fail Counter:** ~$token.failcount~/~$token.maxfail~
      ~end~
      ~end~
      ~if cond=$token.failcount < 10~
      ~attachment title=$user.name color="green"~
      **Token Serial:** ~$token.serial~
      **Token Type**: ~$token.tokentype~
      **Fail Counter:** ~$token.failcount~/~$token.maxfail~
      ~end~
      ~end~
      ~end~
      ~end~
      ~end~
      ~attachment title=$task.name color="white" footer="Pan-Net Infra Security"~
      ~end~
  token_reset:
    body: |
      ~each var=$results~
      ~if cond=$item.result == true~
      ~attachment color="green"~
      Successfully reset failcounter for all tokens belonging to ~$item.name~
      ~end~
      ~end~
      ~if cond=$item.result == false~
      ~attachment color="red"~
      Could not reset all tokens for ~$item.name~
      ~end~
      ~end~
      ~end~
      ~attachment title=$task.name color="white" footer="Pan-Net Infra Security"~
      ~end~
  token_delete:
    body: |
      ~each var=$results as=token~
        ~if cond=$token.result == 0~
          ~attachment title=$token.serial color="red"~
      The token was not deleted (Are you sure it exists?).
          ~end~
          ~end~
        ~if cond=$token.result == 1~
          ~attachment title=$token.serial color="green"~
      Token deleted successfully.
          ~end~
        ~end~
      ~end~
      ~attachment title=$task.name color="white" footer="Pan-Net Infra Security"~
      ~end~
